<?php

namespace AppBundle\Repository;

/**
 * ShippingAddressRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShippingAddressRepository extends \Doctrine\ORM\EntityRepository
{
}
